spring:
  data:
    mongodb:
      username: mongo
      password: mongo
      host: localhost
      port: 27017
      database: commerce
      authentication-database: admin
eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081
