spring:
  liquibase:
    change-log:
      classpath:db/master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/commerce
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8083
      

