spring:
  liquibase:
    change-log:
      classpath:db/master.xml

  datasource:
    hikari:
      connection-timeout: 10000
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/commerce

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082