spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:io.munkush.app.services.kafka.OrderConfirmation
