spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8585/realms/e-commerce/protocol/openid-connect/certs